### PR TITLE
POL-247 New Resource Table 9

### PR DESCRIPTION
**Pull request by SheikSena**
### Description

New Resource Table 9

### Contribution Check List

- [ ] All tests pass.
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable
- [ ] New functionality has been documented in CHANGELOG.MD

### CODE REVIEW

**Comment by SheikSena** [comment]
@cdwilhelm, All the CHANGELOG files are following a different format should I change files to the New Format (The way we are following now) ?.Thanks

**Comment by cdwilhelm** [comment]
> @cdwilhelm, All the CHANGELOG files are following a different format should I change files to the New Format (The way we are following now) ?.Thanks

@SheikSena yes please.

**Comment by SheikSena** [comment]
@cdwilhelm, I have updated all the CHANGELOG files to the new format.

**Comment by cdwilhelm** [comment]
Looks good.  thank you!

**Comment by cdwilhelm** [comment]
@SheikSena can you please fix the conflicts on this PR

**Pull request merged**
