### PR TITLE
CMLS-22: Adding default_frequency "daily"

### PR DESCRIPTION
**Pull request by FabriceScoupeFlexera**
### Description

For (valid) cost policies that don't already have one, add a default frequency (daily), to override the 15 mns set in UI and API by default otherwise.

Changes generated via script:
```
#!/usr/bin/bash
DEFAULT_FREQUENCY="daily"
TEMPLATE_TOPDIR="cost"
echo "Finding template files..."
POLICY_TEMPLATE_FILES=`find $TEMPLATE_TOPDIR -name \*.pt -exec egrep -L default_frequency {} \;`

for f in $POLICY_TEMPLATE_FILES; do
  echo "Processing: `basename $f`"
  d=`dirname $f`; echo "  dirname: $d"
  changelog=$d/CHANGELOG.md; echo "  changelog: $changelog"
  v_changelog=`egrep -m1 -o 'v[0-9]+\.[0-9]+' $changelog | sed 's/v//'`; echo "  version(C): $v_changelog"
  [[ ! -z $v_changelog ]] || continue # No version in changelog? Skip!
  v_template=`egrep -m1 -o 'version\s*:\s*"[0-9]+\.[0-9]+' $f | sed 's/.*"//'`; echo "  version(T): $v_template"
  [[ ! -z $v_template ]] || continue # No version in template? Skip!
  [[ "$v_changelog" == "$v_template" ]] || continue # Inconsistent versions? Skip!
  new_version=`echo $v_template | perl -lane '/(\d+)\.(\d+)/&&print "$1.",$2+1'`; echo "  new version: $new_version"
  sed 's/\(^\s*version\s*:\s*"\)'$v_template'/\1'$new_version'/' $f > $f.mod; echo "  patch1:"; diff $f $f.mod
  sed 's/^\(info.*\)/default_frequency "'$DEFAULT_FREQUENCY'"\n\1/' $f.mod > $f.mod2
  mv $f.mod2 $f.mod; echo "  patch2:"; diff $f $f.mod
  echo "  `basename $f` patched."
  sed '1,1s/.*/&\n\n## v'$new_version'\n\n- Added default_frequency "'$DEFAULT_FREQUENCY'"/' $changelog > $changelog.mod  echo "patch:"; diff $changelog $changelog.mod
  echo " CHANGELOG.md patched."
  mv $f.mod $f
  mv $changelog.mod $changelog
done
```

### Issues Resolved

https://jira.flexera.com/browse/CMLS-22

### Contribution Check List

- [ ] All tests pass.
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable
- [x] New functionality has been documented in CHANGELOG.MD

### CODE REVIEW

**Review by douglaswth — APPROVED** [review]
This looks good. I'm wondering if something could be added to the Dangerfile to check that Policy Template files all have a `default_frequency` specified to help ensure that when new ones are added a good default is considered.

**Review by Haydenmarx — DISMISSED** [review]
LGTM

**Comment by srpomeroy** [comment]
> This looks good. I'm wondering if something could be added to the Dangerfile to check that Policy Template files all have a `default_frequency` specified to help ensure that when new ones are added a good default is considered.

Just added this.

**Review by rshade — APPROVED** [review]
since @Haydenmarx previously reviewed and I just bumped the eol fix. I am marking LGTM.

**Pull request merged**
