### PR TITLE
Fix trim vuln

### PR DESCRIPTION
**Pull request by gonzalez**
### Description

updating trim to fix vulnerability issue.
https://github.com/flexera/policy_templates/security/dependabot/package-lock.json/trim/open

### Issues Resolved

The version of trim used is vulnerable.

### Contribution Check List

- [ ] All tests pass.
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable
- [ ] New functionality has been documented in CHANGELOG.MD

### CODE REVIEW

**Comment by douglaswth** [comment]
Could you provide a link to explain what vulnerability this is fixing?

**Comment by rshade** [comment]
it won't actually fix it, yet, its a hard pin upstream: https://github.com/textlint/textlint/issues/717

**Comment by gonzalez** [comment]
@douglaswth 
https://github.com/flexera/policy_templates/security/dependabot/package-lock.json/trim/open

**Review by srpomeroy — APPROVED** [review]
LGTM. We should update the link to the rule config once the source repo has been updated.

**Pull request merged**
