### PR TITLE
Removed legacy CMP permission validation declaration

### PR DESCRIPTION
**Pull request by gonzalez**
### Description

The policy required users to have read permissions on legacy CMP credential manager, which was causing error for users without legacy CMP permissions. In addition, the policy does not make use of legacy CMP credentials.

### Contribution Check List

- [x] All tests pass.
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable
- [x] New functionality has been documented in CHANGELOG.MD

### CODE REVIEW

**Comment by douglaswth** [comment]
I think you should be able to fix two of the Danger errors by enclosing those example URLs in backticks (`).

**Review by srpomeroy — APPROVED** [review]
LGTM

**Review by rshade — APPROVED** [review]
LGTM

**Review by srpomeroy — APPROVED** [review]
LGTM

**Pull request merged**
